expose facial transformation matrix in MediaPipeFaceLandmarkerResult
j20001970/GDMP pull request #21
Opened 2023-07-31 02:53 UTC by you-win

2023-08-01 06:12 UTC, j20001970 requested changes

2023-08-02 01:16 UTC, you-win commented on GDMP/tasks/vision/face_landmarker.cc
>  			&MediaPipeFaceLandmarker::initialize, DEFVAL(RUNNING_MODE_IMAGE), DEFVAL(1), DEFVAL(0.5), DEFVAL(0.5), DEFVAL(0.5), DEFVAL(false));
Updated the PR

2023-08-02 04:19 UTC, j20001970 approved these changes

2023-08-02 04:19 UTC, merged

2023-08-02 04:19 UTC, j20001970 commented
Thanks!